# Generated by Django 5.2.8 on 2025-11-30 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='glos',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='glos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosy', to='forum.post'),
        ),
        migrations.AddField(
            model_name='watek',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watki', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watek',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watki', to='forum.kategoria'),
        ),
        migrations.AddField(
            model_name='post',
            name='watek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posty', to='forum.watek'),
        ),
        migrations.AlterUniqueTogether(
            name='glos',
            unique_together={('uzytkownik', 'post')},
        ),
    ]
